apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project
spec:
  template:
    metadata:
      name: nginx
      labels:
        apps: test-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      apps: test-app